name: Move to QA column

on:
  pull_request:
    types:
      - closed

jobs:
  move_to_qa:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    steps:
      - name: Move to QA
        uses: alex-page/github-project-automation-plus@v0.6.0
        with:
          project: Board
          column: QA
          repo-token: ${{ secrets.CERN_SIS_BOT_PAT }}
          action: 'move'
