name: Move from In Progress to Review

on:
  issues:
    types:
      - labeled

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
        with:
          action-token: ${{ secrets.CERN_SIS_BOT_PAT }} 
          project-url: https://github.com/orgs/cern-sis/projects/1
          column-name: "Review"
          label-name: "ready-to-review"

